### ISSUE TITLE
AttributeError: 'WebPage' object has no attribute 'setWebChannel'

### ISSUE THREAD

**Issue by FelipeSavazii** [IanTerzo/Neutron#22]
```
[savazi@savazi IQ Option App]$ /bin/python "/home/savazi/Documentos/Python/Freelas/IQ Option App/main.py"
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Traceback (most recent call last):
  File "/home/savazi/Documentos/Python/Freelas/IQ Option App/main.py", line 13, in <module>
    win.show()
  File "/home/savazi/.local/lib/python3.10/site-packages/Neutron/__init__.py", line 179, in show
    webview.start(self.load_handler, self.webview)
  File "/home/savazi/.local/lib/python3.10/site-packages/webview/__init__.py", line 140, in start
    guilib.create_window(windows[0])
  File "/home/savazi/.local/lib/python3.10/site-packages/webview/platforms/qt.py", line 654, in create_window
    _create()
  File "/home/savazi/.local/lib/python3.10/site-packages/webview/platforms/qt.py", line 638, in _create
    browser = BrowserView(window)
  File "/home/savazi/.local/lib/python3.10/site-packages/webview/platforms/qt.py", line 306, in __init__
    self.view.page().setWebChannel(self.channel)
AttributeError: 'WebPage' object has no attribute 'setWebChannel'
```
My error

**Comment by IanTerzo** [comment]
Try updating pywebview:
`pip install pywebview --upgrade`

**Comment by jpotyka** [comment]
Wouldn't it make sense to define the version of the dependencies of neutron in the setup.py with a lower limit?

**Comment by IanTerzo** [comment]
> Wouldn't it make sense to define the version of the dependencies of neutron in the setup.py with a lower limit?

You are probably right.

Closing the issue i assume updating pywebview solved the problem
